export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const ADD_NEW_BUDGET_LOADING = 'ADD_NEW_BUDGET_LOADING';
export const ADD_NEW_BUDGET_SUCCESS = 'ADD_NEW_BUDGET_SUCCESS';
export const ADD_NEW_BUDGET_FAIL= 'ADD_NEW_BUDGET_FAIL';

export const GET_ALL_BUDGETS_LOADING = 'GET_ALL_BUDGETS_LOADING';
export const GET_ALL_BUDGETS_SUCCESS = 'GET_ALL_BUDGETS_SUCCESS';
export const GET_ALL_BUDGETS_FAIL= 'GET_ALL_BUDGETS_FAIL';

export const ADD_NEW_INST_LOADING='ADD_NEW_INST_LOADING';
export const ADD_NEW_INST_SUCCESS='ADD_NEW_INST_SUCCESS';
export const ADD_NEW_INST_FAIL='ADD_NEW_INST_FAIL';

export const GET_ALL_INST_LOADING='GET_ALL_INST_LOADING';
export const GET_ALL_INST_SUCCESS='GET_ALL_INST_SUCCESS';
export const GET_ALL_INST_FAIL='GET_ALL_INST_FAIL';

export const GET_ONE_INST_LOADING='GET_ONE_INST_LOADING';
export const GET_ONE_INST_SUCCESS='GET_ONE_INST_SUCCESS';
export const GET_ONE_INST_FAIL='GET_ONE_INST_FAIL';

export const DELETE_INST_LOADING="DELETE_INST_LOADING";
export const DELETE_INST_SUCCESS="DELETE_INST_SUCCESS";
export const DELETE_INST_FAIL="DELETE_INST_FAIL";

export const UPDATE_INST_LOADING = 'UPDATE_INST_LOADING';
export const UPDATE_INST_SUCCESS = 'UPDATE_INST_SUCCESS';
export const UPDATE_INST_FAIL= 'UPDATE_INST_FAIL';

export const REGISTER_USER_LOADING="REGISTER_USER_LOADING";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL";

export const GET_ALL_USER_LOADING="GET_ALL_USER_LOADING";
export const GET_ALL_USER_SUCCESS="GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL="GET_ALL_USER_FAIL";

export const DELETE_USER_LOADING="DELETE_USER_LOADING";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL="DELETE_USER_FAIL";

export const NEW_REQUEST_LOADING="NEW_REQUEST_LOADING";
export const NEW_REQUEST_SUCCESS="NEW_REQUEST_SUCCESS";
export const NEW_REQUEST_FAIL="NEW_REQUEST_FAIL";

export const GET_REQUESTS_LOADING="GET_REQUESTS_LOADING";
export const GET_REQUESTS_SUCCESS="GET_REQUESTS_SUCCESS";
export const GET_REQUESTS_FAIL="GET_REQUESTS_FAIL";

export const GET_REQUEST_LOADING="GET_REQUEST_LOADING";
export const GET_REQUEST_SUCCESS="GET_REQUEST_SUCCESS";
export const GET_REQUEST_FAIL="GET_REQUEST_FAIL";

export const ADD_REVIEWER_LOADING="ADD_REVIEWER_LOADING";
export const ADD_REVIEWER_SUCCESS="ADD_REVIEWER_SUCCESS";
export const ADD_REVIEWER_FAIL="ADD_REVIEWER_FAIL";

export const REMOVE_REVIEWER_LOADING="ADD_REVIEWER_LOADING";
export const REMOVE_REVIEWER_SUCCESS="ADD_REVIEWER_SUCCESS";
export const REMOVE_REVIEWER_FAIL="ADD_REVIEWER_FAIL";

export const ADD_COMMENT_LOADING="ADD_COMMENT_LOADING";
export const ADD_COMMENT_SUCCESS="ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL="ADD_COMMENT_FAIL";

export const SEND_REVIEW_LOADING="SEND_REVIEW_LOADING";
export const SEND_REVIEW_SUCCESS="SEND_REVIEW_SUCCESS";
export const SEND_REVIEW_FAIL="SEND_REVIEW_FAIL";

export const CHANGE_STATUS_LOADING="CHANGE_STATUS_LOADING";
export const CHANGE_STATUS_SUCCESS="CHANGE_STATUS_SUCCESS";
export const CHANGE_STATUS_FAIL="CHANGE_STATUS_FAIL";

export const APPROVE_BUDGET_LOADING="APPROVE_BUDGET_LOADING";
export const APPROVE_BUDGET_SUCCESS="APPROVE_BUDGET_SUCCESS";
export const APPROVE_BUDGET_FAIL="APPROVE_BUDGET_FAIL";

export const GET_BUDGET_LOADING="GET_MY_BUDGET_LOADING";
export const GET_BUDGET_SUCCESS="GET_MY_BUDGET_SUCCESS";
export const GET_BUDGET_FAIL="GET_MY_BUDGET_FAIL";


export const GET_ALL_TRANSACTIONS_FAIL="GET_ALL_TRANSACTIONS_FAIL";
export const GET_ALL_TRANSACTIONS_LOADING="GET_ALL_TRANSACTIONS_LOADING";
export const GET_ALL_TRANSACTIONS_SUCCESS="GET_ALL_TRANSACTIONS_SUCCESS";

export const CHANGE_PASSWORD_LOADING="CHANGE_PASSWORD_LOADING";
export const CHANGE_PASSWORD_SUCCESS="CHANGE PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL="CHANGE_PASSWORD_FAIL";

export const ADD_TRANSACTION_LOADING="ADD_TRANSACTION_LOADING";
export const ADD_TRANSACTION_SUCCESS="ADD_TRANSACTION_SUCCESS";
export const ADD_TRANSACTION_FAIL="ADD_TRANSACTION_FAIL";

export const ADD_CATEGORY_LOADING="ADD_CATEGORY_LOADING";
export const ADD_CATEGORY_SUCCESS="ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL="ADD_CATEGORY_FAIL";

export const GET_ALL_CATEGORY_LOADING="GET_ALL_CATEGORY_LOADING";
export const GET_ALL_CATEGORY_SUCCESS="GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAIL="GET_ALL_CATEGORY_FAIL";

