export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const ADD_NEW_BUDGET_LOADING = 'ADD_NEW_BUDGET_LOADING';
export const ADD_NEW_BUDGET_SUCCESS = 'ADD_NEW_BUDGET_SUCCESS';
export const ADD_NEW_BUDGET_FAIL= 'ADD_NEW_BUDGET_FAIL';

export const GET_ALL_BUDGETS_LOADING = 'GET_ALL_BUDGETS_LOADING';
export const GET_ALL_BUDGETS_SUCCESS = 'GET_ALL_BUDGETS_SUCCESS';
export const GET_ALL_BUDGETS_FAIL= 'GET_ALL_BUDGETS_FAIL';

export const ADD_NEW_INST_LOADING='ADD_NEW_INST_LOADING';
export const ADD_NEW_INST_SUCCESS='ADD_NEW_INST_SUCCESS';
export const ADD_NEW_INST_FAIL='ADD_NEW_INST_FAIL';

export const GET_ALL_INST_LOADING='GET_ALL_INST_LOADING';
export const GET_ALL_INST_SUCCESS='GET_ALL_INST_SUCCESS';
export const GET_ALL_INST_FAIL='GET_ALL_INST_FAIL';

export const GET_ONE_INST_LOADING='GET_ONE_INST_LOADING';
export const GET_ONE_INST_SUCCESS='GET_ONE_INST_SUCCESS';
export const GET_ONE_INST_FAIL='GET_ONE_INST_FAIL';

export const DELETE_INST_LOADING="DELETE_INST_LOADING";
export const DELETE_INST_SUCCESS="DELETE_INST_SUCCESS";
export const DELETE_INST_FAIL="DELETE_INST_FAIL";

export const UPDATE_INST_LOADING = 'UPDATE_INST_LOADING';
export const UPDATE_INST_SUCCESS = 'UPDATE_INST_SUCCESS';
export const UPDATE_INST_FAIL= 'UPDATE_INST_FAIL';

export const REGISTER_USER_LOADING="REGISTER_USER_LOADING";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL";

export const GET_ALL_USER_LOADING="GET_ALL_USER_LOADING";
export const GET_ALL_USER_SUCCESS="GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL="GET_ALL_USER_FAIL";

export const DELETE_USER_LOADING="DELETE_USER_LOADING";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL="DELETE_USER_FAIL";





